version: "3"
services:
  mysql_db:
    image: mysql:latest
    environment:
      MYSQL_USER: baggy
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: docker_test
    ports:
      - 27017:27017
    volumes:
      - mysql_data_container:/data/db

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redis_data_container:/data

volumes:
  mysql_data_container:
  redis_data_container:
